language: php

php:
  - 7.1.8

before_script:
  - cp .env.exemple .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
